language: R
r_conda_packages:
  r-rmarkdown: latest
r_cran_packages:
  MASS: latest
  dplyr: latest
  ggplot2: latest
  gtable: latest
  isoband: latest
  knitr: latest
  lubridate: latest
  mgcv: latest
  prettydoc: latest
  scales: latest
title: r html example 2
type: markdown
version: 3.4
