language: R
r_packages:
- package: DT
  code: install.packages("DT", dependencies = TRUE, repos = "http://cran.us.r-project.org")
- package: nortest
  method: cran
- package: pbkrtest
  method: cran
  version: latest
- package: r-devtools
  channel: r
  method: conda
- package: r-lme4
  channel: conda-forge
  method: conda
- package: RcmdrMisc
  method: cran
  version: latest
  dependencies: true
- package: car
  dependencies: true
  method: cran
- package: lmtest
  method: cran
- package: shiny
  method: cran
- package: shinythemes
  method: cran
- package: tidyverse/ggplot2
  method: github
- package: tseries
  method: cran
title: R shiny Example
type: shiny
version: 3.6
